---
title: "Semantic Reasoning with Natural Language Understanding-based Interaction for Controlling Lumen Social Robot"
author: "Hendy Irawan"
date: "Tuesday, June 23, 2015"
output:
  html_document:
    self_contained: no
---

**Penalaran Semantik dengan Interaksi Berbasis Pemahaman Bahasa Alami untuk Mengendalikan Robot Sosial Lumen**

1. [Preface (Kata Pengantar)](chapter1.html)
2. [Acknowledgments (Ucapan Terima Kasih)](acknowledgments.html)

Hendy's internal notes:

1. Robot need behavior
2. need to reason with goals
3. understand semantic of actions
4. play with children
5. natural language understanding in English
6. networked/distributed processing
7. connection with other modules like speech recognition, speech synthesis, database, face recognition, human recognition, object recognition, scene perception
8. goals:
1. can play tic tac toe, using natural language
2. can tell story, using natural language
9. interact in social media with Twitter
10. Use [http://gist.neo4j.org/?github-kbastani%2Fgists%2F%2Fmeta%2FTimeScaleEventMetaModel.adoc](Kenny Bastani's Time scale event meta model)

Bayesian Network library/framework:

1. [**H2O**](http://h2o.ai/). Two best techs with regard to Spark/Spark Streaming is H2O and Spark MLlib. Now H2O is more of a competitor to Spark than to Mahout. In a way, Spark+MLlib competes with H2O. So you can use just H2O without Spark, but if your data is already in Spark (RDD/HDFS) then you can use [Sparkling Water](https://databricks.com/blog/2014/06/30/sparkling-water-h20-spark.html).
2. [Weka](http://www.cs.waikato.ac.nz/ml/index.html). Most mature, but does it work well with Spark/Spark Streaming?
3. [Spark MLlib](https://spark.apache.org/mllib/). With MLlib, you can't use H2O, since it only runs on Spark. So maybe this will be out soon. "Mahout focusses on algorithms for which there is a wide-spread need for scalable algorithms.  MLlib is considerably more liberal with what is brought in." See [Mahout's take on comparison with MLlib](http://www.weatheringthroughtechdays.com/2015/04/mahout-010x-first-mahout-release-as.html).
4. [-Mahout-](http://mahout.apache.org) (out for the moment, [H2O can be used without Mahout, but Mahout can be an environment that executes on top of both H2O and Spark](https://www.quora.com/How-is-0xdatas-H2O-different-from-Apache-Mahout/answer/Cliff-Click-1)). superior](https://www.quora.com/How-is-0xdatas-H2O-different-from-Apache-Mahout/answer/Cliff-Click-1))
5. [-Jayes / Eclipse Code Recommenders-](https://www.eclipse.org/recommenders/jayes/) (out: I prefer a general purpose AI library).
6. [Deeplearning4j.org is an open-source, distributed deep learning framework for the JVM.](http://deeplearning4j.org/)
7. unbbayes
8. javabayes

Using H2O, you can use any of R, REST/JSON (e.g. curl/bash), GUI (browser), Java or Scala.  H2O algo's are typically 100x to 1000x faster than current Map/Reduce-based Mahout (but Mahout is working hard to port itself to both Spark and H2O).  As Hrvoje mentioned, H2O has fewer algos implemented:

* DeepLearning / Neural Nets
* Random Forest
* Gradient Boosted Method
* Generalized Linear Modeling (including Logistic Regression, Poisson, Gamma)
* PCA
* KMeans (KMeans++, KMeans||, K-modes)
* Naive Bayes
* General Data Munging (any standard R expression which auto-broadens to cover arrays also works the same in H2O)
